### PR TITLE
Make plugin compatible to Jenkins Pipeline plugin

### PR DESCRIPTION
**Pull request by EmteZogaf**
A simple implementation of `SimpleBuildStep`. Creating a dummy `FreeStyleBuild` and only setting properties which are needed by `CommandInterpreter#perform(AbstractBuild, Launcher, TaskListener)`.

### CODE REVIEW

**Comment by kinow** [comment]
Hi @EmteZogaf ,

Thank you for the pull request.

I have another plugin that received a similar pull request, so I already have in my TODO list to sit down, and spend some hours learning the internals of the Jenkins Pipeline plug-in, and how to add support for it in other plug-ins.

I thought given the simplicity of the R plug-in your PR could be a good primer for me, so that I could learn a little bit more about the Jenkins Pipeline plug-in, but looks like in order to include a CommandInterpreter you have to use a BuildStep? Interesting. I'll need a bit more of time to understand why, then will merge and cut a new release ;)

If you have some pointers to educate me on the pipeline plug-in, feel free to paste them here.

Thanks again
Bruno

**Comment by EmteZogaf** [comment]
I just followed https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md#build-steps but I still need time to figure where to configure the `PATH` as the `RScript` executable is currently not found when called from pipeline script.

**Comment by EmteZogaf** [comment]
It's still not working in a workflow/pipeline project because of [JENKINS-29144](https://issues.jenkins-ci.org/browse/JENKINS-29144). The build step is not getting the `PATH` environment variable and hence cannot find the `RScript` executable. Hope they will fixed it soon...

**Comment by kinow** [comment]
Thanks @EmteZogaf 

Feel free to keep the PR up to date as necessary, and ping me in case you need anything and I take too long to reply here.

**Comment by EmteZogaf** [comment]
It's working for me now. I tried it with local (master) executor and a ssh slave. I tried it with both Jenkins versions 1.580.1 and 2.7.1.

**Comment by EmteZogaf** [comment]
The current implementation is just a quick hack to be able to use R scripts inside pipeline scripts. But it blocks the groovy process executing the pipeline script till the R process returns.

We should use the [step api](https://github.com/jenkinsci/workflow-step-api-plugin) like the [DurableTaskStep](https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java) does. I'll give it a try in the upcoming weeks.

**Comment by EmteZogaf** [comment]
As lazy as a sloth I copied the implementation of [ShellStep](https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java) and call the R script from inside the shell script.

**Comment by kinow** [comment]
Laziness is a bless @EmteZogaf  :)

Is this PR ready to be reviewed? Or is there anything else missing?

**Comment by EmteZogaf** [comment]
I'll test it today in production server and will give you report.

**Comment by Le0Michine** [comment]
I will check once again and create a new release this weekend

**Comment by kinow** [comment]
Hi @Le0Michine I'm the maintainer of the r-plugin. Are you talking about releasing the R plug-in this weekend?

**Comment by kinow** [comment]
Hi @EmteZogaf , reverted the merge. Can you submit again your pull request once it's done, and let me know how your test in the production server went. Still rolling a development cycle for BioUno plug-ins, so will cut a new release of image-gallery, active-choices, r-plugin, etc, in the next days. So we can include your change too.

**Comment by Le0Michine** [comment]
@kinow sorry man, I just though it is my plugin because I received a notification, I won't do anything at the evening after hard work :)

**Comment by kinow** [comment]
Not a problem @Le0Michine 

I think by default GitHub subscribes you to all repositories in your organisations (or it used to do that). I disabled that option in my profile settings, to reduce the amount of notifications (-:

In case you ever feel like contributing and even co-maintaining r-plugin or any other plug-in, just drop a note or send some pull requests :+1

**Comment by EmteZogaf** [comment]
Ok, thx. It's currently working so far as expected. I'll try some more advanced and long-lasting scripts today and see, if the durability feature is given (restart jenkins during build).

**Comment by EmteZogaf** [comment]
Restarting jenkins during pipeline build, re-establishing connection to running R process and completing build works fine. I'll re-submit pr.

**Comment by EmteZogaf** [comment]
see #4

**Pull request merged**
