### PR TITLE
Add Jenkins Pipeline compatibility

### PR DESCRIPTION
**Pull request by EmteZogaf**
These changes allow the usage of R plugin in pipeline scripts.

Re-submit of #1 because of accidental merge before review.

### CODE REVIEW

**Comment by kinow** [comment]
Looks nice @EmteZogaf 

Will give it a try tonight, and if I can run an R script as before, and also within a pipeline, will merge and release :D 

Thanks!

**Comment by kinow** [comment]
Actually, had to kill some time, so could test it right now :tada: 

Used following script:

```
a <- c(1,2,3,4)
plot(a)
```

Success with normal freestyle job.

Success with pipeline job too, using:

```
node {
   rscript '''
   a <- c(1,2,3,4)
   plot(a)
   '''
}
```

@EmteZogaf how do you feel about changing from rscript to r, the function name?

**Comment by EmteZogaf** [comment]
OK, single-char commands look a bit strange to me. That's why I chose `rscript`. But like this is called _r-plugin_ and not _rscript-plugin_ it should be `r`.

**Comment by kinow** [comment]
Indeed @EmteZogaf , but since the language, plug-in, and file extension are "r", that was the first thing I tried (though I could have used the helper screens to pre-populate scripts or found in the code what was the func name).

Are you going to update the pull request, or should I merge and update it?

**Comment by EmteZogaf** [comment]
Updated

**Comment by kinow** [comment]
Thanks @EmteZogaf ! Preparing a release now.

**Comment by kinow** [comment]
Done. Announced in the [biouno mailing list](https://groups.google.com/forum/#!topic/biouno-users/c8b67DS2tmY). Was also going to update a Wiki page, that I saw some time ago... I am quite sure there was a Wiki page with the list of plug-ins with pipeline compatibility, but alas I could not locate it.

Thanks again @EmteZogaf

**Comment by EmteZogaf** [comment]
Thanks for accepting the changes.
I found this list https://github.com/jenkinsci/pipeline-plugin/blob/master/COMPATIBILITY.md

**Comment by kinow** [comment]
That's the one that I had seen before. PR sent https://github.com/jenkinsci/pipeline-plugin/pull/427

Thanks!

**Comment by jglick** [comment]
FWIW I do not think this kind of step is a good idea. Better left to libraries or macros.

But, see [JENKINS-37011](https://issues.jenkins-ci.org/browse/JENKINS-37011) & [JENKINS-26055](https://issues.jenkins-ci.org/browse/JENKINS-26055).

**Pull request merged**
